import requests
import time
import sys
import os

def main(args):
    token = os.getenv('token')
    droplet = args.get("droplet", "")
    url_base = "https://api.digitalocean.com/v2/droplets/" + droplet
    headers = {"Authorization": "Bearer " + token}
    

    url_trigger_snapshot_creation = url_base + "/actions"
    data = {"type":"snapshot", "name":"autogenerated_" + time.strftime("%Y_%m_%d_%H_%M")}
    trigger_snapshot_creation = requests.post(url_trigger_snapshot_creation, headers=headers, json=data)
    if trigger_snapshot_creation.status_code == 201:
        print("New snapshot " + data["name"] + " successfully triggered for creation.")
    else:
        print("There was an error while triggering snapshot creation.")
        exit()

    url_list_snapshots = url_base + "/snapshots"
    list_snapshots = requests.get(url_list_snapshots, headers=headers).json()
    for value in list_snapshots['snapshots']:
        if "autogenerated" in value['name']:
            url_trigger_snapshot_deletion = "https://api.digitalocean.com/v2/snapshots/" + str(value['id'])
            trigger_snapshot_deletion = requests.delete(url_trigger_snapshot_deletion, headers=headers)
            if trigger_snapshot_deletion.status_code == 204:
                print("Existing snapshot " + value['name'] + " successfully triggered for deletion.")
            else:
                print("There was an error while triggering snapshot deletion.")
                exit()
    return {}
