parameters: {}
environment: {}
packages:
    - name: do-snap
      shared: false
      environment:
        token: ""                                 # Personal access token needed here.
      parameters: {}
      annotations: {}
      functions:
        - name: your-droplet-name                 # Change to your Droplet's name or group name (e.g., "front-end-server" or "production-droplets").
          binary: false
          main: ""
          runtime: python:default
          web: false
          parameters: {}
          environment:
            droplets: ""                           # Provide Droplet ID or comma-separated list of Droplet IDs.
          limits:
            timeout: 60000
          triggers:
            - name: snap-your-droplet-name         # Change to your trigger name (e.g., "every-six-hours").
              sourceType: scheduler
              sourceDetails:
                cron: "0 */6 * * *"                # Adjust cron schedule (runs every 6 hours by default).
