parameters: {}
environment: {}
packages:
    - name: snapshot
      shared: false
      environment:
        token: ${token}
        droplet: ${droplet}
      parameters: {}
      annotations: {}
      functions:
        - name: droplet
          binary: false
          main: ""
          runtime: python:default
          parameters: {}
          environment: {}
          annotations: {}
          limits:
            timeout: 60000
