parameters: {}
environment: {}
packages:
    - name: do-snap
      shared: false
      environment:
        token: ""                                 # Provide your personal access token.
      parameters: {}
      annotations: {}
      functions:
        - name: your-droplet-name                 # Rename to your Droplet's name.
          binary: false
          main: ""
          runtime: python:default
          web: false
          parameters: {}
          environment:
            droplets: ""                           # Provide your Droplet ID.
          limits:
            timeout: 60000
          triggers:
            - name: snap-your-droplet-name        # Rename to your Droplet's name.
              sourceType: scheduler
              sourceDetails:
                cron: "0 */6 * * *"               # Adjust cron schedule (runs every 6 hours by default).
