parameters: {}
environment: {}
packages:
    - name: snapshot
      shared: false
      environment:
        token: ${token}
      parameters: {}
      annotations: {}
      functions:
        - name: your-droplet-name
          binary: false
          main: ""
          runtime: python:default
          parameters: {}
          environment:
            droplet: ${droplet}
          annotations: {}
          limits:
            timeout: 60000
          triggers:
          - name: snapshot-cron
            sourceType: scheduler
            sourceDetails:
              cron: "0 */3 * * *"
