parameters: {}
environment: {}
packages:
    - name: do-snap
      shared: false
      environment:
        token: "dop_v1_590bf6139ac5cc429640eae2ed6efc2df4aa04ed5fda2164c54bd3491bbec5b3"
      parameters: {}
      annotations: {}
      functions:
        - name: your-droplet-name
          binary: false
          main: ""
          runtime: python:default
          web: false
          parameters: {}
          environment:
            droplet: "974654061"
          limits:
            timeout: 60000
          triggers:
            - name: snap-your-droplet-name
              sourceType: scheduler
              sourceDetails:
                cron: "0 */6 * * *"