import requests
import time
import os

def main(args):
    # Ingesting token.
    token = os.getenv('token', None)
    if not token:
        return {"body": "No token provided. Terminating."}

    # Ingesting Droplet ID.
    droplets = os.getenv("droplets", None)
    if not droplets:
        return {"body": "No Droplet IDs provided. Terminating."}
    droplets = droplets.split(',')

    # Looping thourgh the list of Droplet IDs
    msg = ''
    body = ''
    for droplet in droplets:
        msg = snap(droplet,token)
        body = body + "Droplet ID: " + droplet + " - " + msg 
    
    # Returning complete final message.
    return {"body": body}

def snap(droplet,token):
    # Building a base URL.
    url_base = "https://api.digitalocean.com/v2/droplets/" + droplet
    headers = {"Authorization": "Bearer " + token}
   
    # Triggering snapshot creation. Snapshot name includes full date and UTC timestamp.
    url_trigger_snapshot_creation = url_base + "/actions"
    data = {"type":"snapshot", "name":"autogenerated_" + time.strftime("%Y_%m_%d_%H_%M")}
    trigger_snapshot_creation = requests.post(url_trigger_snapshot_creation, headers=headers, json=data)
    if not trigger_snapshot_creation.status_code == 201:
        msg = "There was an error while triggering snapshot creation. "
    else:
        msg = "New snapshot successfully triggered for creation: " + data["name"] + ". "
    
    # Triggering snapshot deletion.
    url_list_snapshots = url_base + "/snapshots"
    list_snapshots = requests.get(url_list_snapshots, headers=headers)
    if not list_snapshots.status_code == 200:
        msg += "There was an error while triggering snapshot deletion. "
    else:
        for value in list_snapshots.json()['snapshots']:
            if "autogenerated" in value['name']:
                url_trigger_snapshot_deletion = "https://api.digitalocean.com/v2/snapshots/" + str(value['id'])
                trigger_snapshot_deletion = requests.delete(url_trigger_snapshot_deletion, headers=headers)
                if not trigger_snapshot_deletion.status_code == 204:
                    msg += "There was an error while triggering snapshot deletion. "
                else:
                    msg += "Existing snapshot successfully triggered for deletion: " + value['name'] + " "
        
    return (msg)

if __name__=="__main__": 
    main()
